name: Build & Publish wheels

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: ubuntu-latest   # x86_64
            label: linux-x86_64
            target: x86_64
          - os: ubuntu-latest   # cross 编 aarch64
            label: linux-aarch64
            target: aarch64

          # macOS
          - os: macos-13        # Intel
            label: macos-intel
            target: x86_64
          - os: macos-14        # Apple Silicon
            label: macos-arm64
            target: aarch64

          # Windows
          - os: windows-latest
            label: win-x86_64
            target: x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: ${{ matrix.target }}
          args: --release --compatibility manylinux_2_28 --interpreter 3.10 3.11 3.12

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.label }}-wheels
          path: target/wheels/*.whl

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: "*-wheels"

      - uses: astral-sh/setup-uv@v4

      - name: Publish
        run: |
          uv publish dist/* --token ${{ secrets.PYPI_API_TOKEN }}
