name: Build & Publish wheels

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: build-${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: linux-x86_64
            os: ubuntu-latest
          - label: linux-aarch64
            os: ubuntu-latest-arm64

          - label: macos-intel
            os: macos-13
          - label: macos-arm64
            os: macos-14

          - label: win-x86_64
            os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --interpreter 3.10 3.11 3.12

      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.label }}-wheels
          path: target/wheels/*

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: "*-wheels"

      - uses: astral-sh/setup-uv@v4

      - name: Publish
        run: |
          uv publish dist/* --token ${{ secrets.PYPI_API_TOKEN }}
